# Generated by Django 5.1 on 2024-08-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
